quarkus.http.port=8081

# Baza podataka
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=Kosarka4
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/music_db

# Hibernate - ISPRAVLJENO (dodato .database.)
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# OIDC / Keycloak
quarkus.oidc.auth-server-url=http://localhost:8080/realms/objektno2
quarkus.oidc.client-id=objektno-app
quarkus.oidc.credentials.secret=Ek6gVBDPa5ripvUvuIeKvOf1XLNRxr4M

# REST Klijenti
# Za IpClient (api.ipify.org)
quarkus.rest-client."org.acme.IpClient".url=https://api.ipify.org

# Za tvoj novi TimeServiceClient (timeapi.io)
quarkus.rest-client."org.acme.TimeServiceClient".url=https://timeapi.io

# Opciono: Ako i dalje koristiš stari klijent u nekom drugom dijelu koda
quarkus.rest-client."org.acme.TimeZonesClient".url=https://timeapi.io