quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=Kosarka4
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/music_db

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.hibernate-orm.jdbc.bi-directional-relation-cache=true


quarkus.oidc.auth-server-url=http://localhost:8080/realms/objektno2
quarkus.oidc.client-id=objektno-app


quarkus.oidc.credentials.secret=Ek6gVBDPa5ripvUvuIeKvOf1XLNRxr4M


quarkus.oidc.roles.role-mappings.admin=admin