quarkus.http.port=8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=Kosarka4
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/music_db

quarkus.hibernate-orm.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.oidc.auth-server-url=http://localhost:8080/realms/objektno2
quarkus.oidc.client-id=objektno-app
quarkus.oidc.credentials.secret=Ek6gVBDPa5ripvUvuIeKvOf1XLNRxr4M

quarkus.rest-client."org.acme.TimeZonesClient".url=https://timeapi.io
quarkus.rest-client."org.acme.IpClient".url=https://api.ipify.org